### ISSUE TITLE
Create user facing views story

### ISSUE THREAD

**Issue by timwaters** [timwaters/learninginleeds#16]
meta issue "story" to track the intial creation of user facing views

- [x] #3 Basic Course view 
- [x] #6 Basic search form and results
- [x] #9 Basic Front End UI

**Comment by timwaters** [comment]
Initial forms and views created. We can make new ones to track more advanced features, additons or modifications
